### ISSUE TITLE
InfluxDB Load task raises "Expecting a not null reference for fieldsToAdd"

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-influxdb#8]
### Describe the issue

With the following flow (InfluDB instance using [InfluxCloud](https://cloud2.influxdata.com/): other tasks are working well):

```yaml
id: influx
namespace: dev.ben

variables:
  influxdb_url: xxxx
  api_token: xxxx
tasks:
  - id: geocoding
    type: io.kestra.plugin.core.http.Request
    uri: https://geocoding-api.open-meteo.com/v1/search?name=Paris&count=1&language=en&format=json

  - id: geo_output
    type: io.kestra.plugin.core.output.OutputValues
    values:
      latitude: '{{ json(outputs.geocoding.body).results[0].latitude ?? 52 }}'
      longitude: '{{ json(outputs.geocoding.body).results[0].longitude ?? 13 }}'

  - id: download_weather_data
    type: io.kestra.plugin.core.http.Download
    uri: https://archive-api.open-meteo.com/v1/archive?latitude={{ outputs.geo_output.values.latitude }}&longitude={{ outputs.geo_output.values.longitude }}&start_date=2024-01-01&end_date=2024-01-01&hourly=temperature_2m


  - id: normalize_data
    type: io.kestra.plugin.jdbc.duckdb.Query
    store: true
    inputFiles:
      data.json: "{{ outputs.download_weather_data.uri }}"
    sql: |
      INSTALL json;
      LOAD json;
      COPY(
        SELECT
          unnest(hourly.time) AS time,
          unnest(hourly.temperature_2m) AS temperature_2m,
          latitude AS latitude,
          longitude AS longitude,
          'Paris' AS city
        FROM '{{workingDir}}/data.json'
      ) TO 
      '{{outputFiles["result.csv"]}}' (HEADER, DELIMITER ',');
    outputFiles:
      - result.csv

  - id: csv_to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ outputs.normalize_data.outputFiles['result.csv'] }}" ## This is a proper ION with rectangular data

  - id: load
    type: io.kestra.plugin.influxdb.Load
    connection:
      url: "{{ vars.influxdb_url }}"
      token: "{{ vars.api_token }}"
    org: "test"
    bucket: "test"
    from: "{{ outputs.csv_to_ion.uri }}"
    measurement: "temperature_2m"
```

the load task raises the following error:

![Image](https://github.com/user-attachments/assets/7b498ef3-5d9f-45e0-a638-331c69e8ef07)

### Environment

- Kestra Version: develop (postgre-ee.preview). Here is the reference of the [execution](https://postgres-ee.preview.dev.kestra.io/ui/executions/dev.ben/influx/3xg98zxYGBJiOnE6AjCSF5/gantt)
